[package]
name = "mc-network-data-types"
version = "0.1.3"
edition = "2021"
author = "Bruce0203 <brucefreedy@gmail.com>"
description = "Minecraft network I/O data types"
repository = "https://github.com/Bruce0203/mc-network-data-types"
license = "MIT"
readme = "README.md"
include = [
    "**/*.rs",
    "Cargo.toml",
]

[dependencies]
derive_more = "0.99.17"

